import Navbar from '../components/Navbar';
import {Montserrat} from 'next/font/google'

export const metadata = {
  title: "My project",
  description: "Generated by Next.js",
};

const montserrat = Montserrat({
  weights: [400, 700],
  styles: ['normal', 'italic'],
  subsets: ['latin-ext'],
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
